# Nombre de la aplicacion
spring.application.name=NiagaraViajesParqueBicentenario

# Configuracion del controlador JDBC para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}


# Muestra las consultas SQL en la consola (util para depuracion)
spring.jpa.show-sql=true

# Configura Hibernate para actualizar el esquema de la base de datos automaticamente
spring.jpa.hibernate.ddl-auto=update
